EXU2_Herrera/EXU2_Herrera/Models/EMPLEADO.cs
namespace EXU2_Herrera.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Data.Entity.Spatial;
    using System.Linq;
    using System.Web.Mvc;

    [Table("EMPLEADO")]
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            USUARIO = new HashSet<USUARIO>();
        }

        [Key]
        public int IDEMPLEADO { get; set; }

        [Required]
        [StringLength(80)]
        public string DNI { get; set; }

        [Required]
        [StringLength(100)]
        public string NOMBRE { get; set; }

        [Required]
        [StringLength(150)]
        public string APELLIDO { get; set; }

        [Required]
        [StringLength(150)]
        public string EMAIL { get; set; }

        [Required]
        [StringLength(50)]
        public string CELULAR { get; set; }

        [Column(TypeName = "text")]
        [Required]
        public string DIRECCION { get; set; }

        [Required]
        [StringLength(1)]
        public string ESTADO { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }

        public List<EMPLEADO> Listar()
        {
            var query = new List<EMPLEADO>();

            try
            {
                using (var db = new Model1())
                {

                    query = db.EMPLEADO.Where(x=>x.ESTADO.Equals("A")).ToList();
                }


            }
            catch (Exception ex)
            {
                throw;
            }

            return query;
        }
        public EMPLEADO Obtener(int id) 
        {
            var query = new EMPLEADO();

            try
            {
                using (var db = new Model1())
                {
                  

                    query = db.EMPLEADO
                            .Where(x => x.IDEMPLEADO == id)
                            .SingleOrDefault();
                }


            }
            catch (Exception ex)
            {
                throw;
            }

            return query;
        }
        public void Guardar()
        {

            try
            {
                using (var db = new Model1())
                {
                    

                    if (this.IDEMPLEADO > 0)
                    {
                        db.Entry(this).State = EntityState.Modified;
                    }
                    else
                    {
                        db.Entry(this).State = EntityState.Added;
                    }
                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        public void Eliminar()
        {

            try
            {
                using (var db = new Model1())
                {

                    db.Entry(this).State = EntityState.Deleted;

                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
}

EXU2_Herrera/EXU2_Herrera/Controllers/EmpleadoController.cs
using EXU2_Herrera.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EXU2_Herrera.Controllers
{
    public class EmpleadoController : Controller
    {
        // GET: Empleado
        public static EMPLEADO objEMPLEADO = new EMPLEADO();
        public ActionResult Index()
        {

                return View(objEMPLEADO.Listar());

        }
        public ActionResult Visualizar(int id)
        {
            return View(objEMPLEADO.Obtener(id));
        }

        //public ActionResult Buscar(string criterio)
        //{
        //    return View(
        //        criterio == null || criterio == ""
        //        ? objEMPLEADO.Listar()
        //        : objEMPLEADO.Buscar(criterio)
        //        );
        //}

        public ActionResult AgregarEditar(int id = 0)
        {

            return View(
                id == 0
                ? new EMPLEADO()
                : objEMPLEADO.Obtener(id)
                );
        }

        public ActionResult Guardar(EMPLEADO model)
        {
            foreach (string key in Request.Form.Keys)
            {
                Debug.WriteLine(key + " " + Request.Form[key]);
            }
            if (ModelState.IsValid)
            {
                model.Guardar();
                return Redirect("~/Empleado/");
            }
            else
            {
                return View("~/Views/Empleado/AgregarEditar", objEMPLEADO);
            }
        }

        public ActionResult Eliminar(int id)
        {
            var data = objEMPLEADO.Obtener(id);
            data.ESTADO = "I";
            data.Guardar();
            return Redirect("~/Empleado/Index");
        }
    }
}

EXU2_Herrera/EXU2_Herrera/Views/Empleado/AgregarEditar.cshtml
@model EXU2_Herrera.Models.EMPLEADO
@{
    ViewBag.Title = "AgregarEditar";
}

<h2>AgregarEditar</h2>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="~/Empleado/Index">Empleado</a>
        </li>
    </ol>
</nav>


@using (Html.BeginForm("Guardar", "Empleado", FormMethod.Post))
{
    @Html.HiddenFor(x => x.IDEMPLEADO)
    <div class="card">
        <div class="card-header">
            Informacion del Empleado
        </div>
        <div class="card-body">
            <div class="form-group">
                <label>DNI</label>
                <div class="input-group">
                    @Html.TextBoxFor(x => x.DNI, new { @class = "form-control", required = "required", placeholder = "DNI" })
                </div>
            </div>
            <div class="form-group">
                <label>NOMBRE</label>
                <div class="input-group">
                    @Html.TextBoxFor(x => x.NOMBRE, new { @class = "form-control", required = "required", placeholder = "NOMBRE" })
                </div>
            </div>
            <div class="form-group">
                <label>APELLIDO</label>
                <div class="input-group">
                    @Html.TextBoxFor(x => x.APELLIDO, new { @class = "form-control", required = "required", placeholder = "APELLIDO" })
                </div>
            </div>
            <div class="form-group">
                <label>EMAIL</label>
                <div class="input-group">
                    @Html.TextBoxFor(x => x.EMAIL, new { @class = "form-control", required = "required", placeholder = "EMAIL", type = "email" })
                </div>
            </div>
            <div class="form-group">
                <label>CELULAR</label>
                <div class="input-group">
                    @Html.TextBoxFor(x => x.CELULAR, new { @class = "form-control", required = "required", placeholder = "CELULAR" })
                </div>
            </div>
            <div class="form-group">
                <label>DIRECCION</label>
                <div class="input-group">
                    @Html.TextBoxFor(x => x.DIRECCION, new { @class = "form-control", required = "required", placeholder = "DIRECCION" })
                </div>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="ESTADO" value="A" checked>
                <label class="form-check-label" for="flexRadioDefault1">
                    ACTIVO
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="ESTADO" value="I">
                <label class="form-check-label" for="flexRadioDefault2">
                    INACTIVO
                </label>
            </div>
        </div>
    </div>

    <br />
    <div class="text-end">
        <button type="submit" class="btn-primary">Guardar</button>
        <a href="~/Empleado" class="btn btn-danger">Cancelar</a>
    </div>
}

EXU2_Herrera/EXU2_Herrera/Views/Empleado/Index.cshtml
@model List<EXU2_Herrera.Models.EMPLEADO>
@{
    ViewBag.Title = "Index";
    int id = 0;
}

<div>
    <a href="~/Empleado/AgregarEditar/" class="btn btn-secondary text-start">Agregar Nuevo Empleado</a>
</div>

@*@using (Html.BeginForm("Index", "Empleado", FormMethod.Post))
{
    <div class="text-end">
        @Html.Label("Buscar: ")
        @Html.TextBox("Criterio")
        <button type="submit" class="btn btn-info">Buscar</button>
    </div>

}*@

<table class="table" id="DatatableP">
    <thead>
        <tr>

            <th style="width:50px; ">Id</th>
            <th style="width:200px; ">Dni</th>
            <th style="width:80px; ">Nombre</th>
            <th style="width:90px; ">Apellidos</th>
            <th style="width:80px; ">Email</th>
            <th style="width:80px; ">Celular</th>
            <th style="width:80px; ">Direccion</th>
            <th style="width:250px;"><center>Acciones</center></th>
        </tr>
    </thead>
    <tbody>
       
        @foreach (var m in Model)
        {
            <tr>
                <td>@(id++)</td>
                <td>@(m.DNI)</td>
                <td>@(m.NOMBRE)</td>
                <td>@(m.APELLIDO)</td>
                <td>@(m.EMAIL)</td>
                <td>@(m.CELULAR)</td>
                <td>@(m.DIRECCION)</td>

                <td style="align-content:center">
                    <a href="~/Empleado/Visualizar/@m.IDEMPLEADO" class="btn btn-xs btn-warning">Visualizar</a>
                    <a href="~/Empleado/AgregarEditar/@m.IDEMPLEADO" class="btn btn-xs btn-primary">Modificar</a>
                    <a href="~/Empleado/Eliminar/@m.IDEMPLEADO" class="btn btn-xs btn-danger" onclick="return confirmar('¿Está seguro de eliminar el registro');">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>

    $(document).ready(function () {
        $('#Horizontal').DataTable({
            "scrollX": true
        });
    });

    $(document).ready(function () {
        $('#Vertical').DataTable({
            "scrollY": "200px",
            "scrollCollapse": true,
            "paging": false
        });
    });

    $(document).ready(function () {
        $('#Default').DataTable({
            "order": [[3, "desc"]]
        });
    });


    $(document).ready(function () {
        $("#DatatableP").DataTable({

            "aLengthMenu": [[2, 3, 5, 10, 25, 50, 100, 200, -1], [2, 3, 5, 10, 25, 50, 100, 200, "Todos"]],
            "bDestroy": true,
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ning?n dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "?ltimo",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });

        $('#ejemplo2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "aLengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "Todos"]]
        });

    });


</script>

EXU2_Herrera/EXU2_Herrera/Views/Empleado/Visualizar.cshtml
@model EXU2_Herrera.Models.EMPLEADO
@{
    ViewBag.Title = "Visualizar";
    string estado;
}
<div>
    <a href="~/Empleado" class="btn btn-secondary text-start">Retroceder</a>
</div>

<div class="card">
    <div class="card-header">
        Visualizar del Empleado
    </div>
    <div class="card-body">
        <div class="form-group">
            <label>DNI</label>
            <div class="input-group">
                @Html.TextBoxFor(x => x.DNI, new { @class = "form-control", required = "required", placeholder = "DNI", disabled = "disabled" })
            </div>
        </div>
        <div class="form-group">
            <label>NOMBRE</label>
            <div class="input-group">
                @Html.TextBoxFor(x => x.NOMBRE, new { @class = "form-control", required = "required", placeholder = "NOMBRE", disabled = "disabled" })
            </div>
        </div>
        <div class="form-group">
            <label>APELLIDO</label>
            <div class="input-group">
                @Html.TextBoxFor(x => x.APELLIDO, new { @class = "form-control", required = "required", placeholder = "APELLIDO", disabled = "disabled" })
            </div>
        </div>
        <div class="form-group">
            <label>EMAIL</label>
            <div class="input-group">
                @Html.TextBoxFor(x => x.EMAIL, new { @class = "form-control", required = "required", placeholder = "EMAIL", type = "email", disabled = "disabled" })
            </div>
        </div>
        <div class="form-group">
            <label>CELULAR</label>
            <div class="input-group">
                @Html.TextBoxFor(x => x.CELULAR, new { @class = "form-control", required = "required", placeholder = "CELULAR", disabled = "disabled" })
            </div>
        </div>
        <div class="form-group">
            <label>DIRECCION</label>
            <div class="input-group">
                @Html.TextBoxFor(x => x.DIRECCION, new { @class = "form-control", required = "required", placeholder = "DIRECCION", disabled = "disabled" })
            </div>
        </div>
        <div class="form-group">
            <label>DIRECCION</label>
            <div class="input-group">
               
                @if (Model.ESTADO == "A") {
                    estado = "Activo";
                } else { estado = "Inactivo"; }
                <input type="text" value="@estado" class = "form-control"  disabled >
               
            </div>

        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="ESTADO" value="A" checked>
            <label class="form-check-label" for="flexRadioDefault1">
                ACTIVO
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="ESTADO" value="I">
            <label class="form-check-label" for="flexRadioDefault2">
                INACTIVO
            </label>
        </div>
    </div>
</div>