EXU2_Herrera/EXU2_Herrera/Controllers/ComprasController.cs
using EXU2_Herrera.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EXU2_Herrera.Controllers
{
    public class ComprasController : Controller
    {
        // GET: Compras
        public static DETALLE_PEDIDO objde = new DETALLE_PEDIDO();
        public static PEDIDO objPed = new PEDIDO();

        public ActionResult Index(string criterio)
        {
            if (criterio == null || criterio == "")
            {

                return View(objde.Listar());
            }
            else
            {
                
                return View(objde.Buscar(criterio));
            }
        }
    }
}

EXU2_Herrera/EXU2_Herrera/Views/Compras/Index.cshtml
@model List<EXU2_Herrera.Models.DETALLE_PEDIDO>
@{
    ViewBag.Title = "Index";
    int id = 0;
    int? suma = 0;
    EXU2_Herrera.Models.CATEGORIA obj = new EXU2_Herrera.Models.CATEGORIA();
}
<div class="input-group mb-3">
    @using (Html.BeginForm("Index", "Compras", FormMethod.Post))
    {
        <label>Buscar por cliente:</label>
        <input class="form-control" type="text" name="criterio" required>
        <br />
        <div class="input-group-append">
            <input type="submit" value="Buscar" class="btn btn-primary" />
        </div>

        
    }
</div>
<table class="table" id="DatatableP">
    <thead>
        <tr>

            <th style="width:50px; ">Id</th>
            <th style="width:200px; ">IDPEDIDO</th>
            <th style="width:200px; ">CATEGORIA</th>
            <th style="width:80px; ">NOMBRE</th>
            <th style="width:90px; ">PRECIO</th>
            <th style="width:80px; ">CANTIDAD</th>
            <th style="width:80px; ">SUBTOTAL</th>

        </tr>
    </thead>
    <tbody>

        @foreach (var m in Model)
        {
            suma = suma + m.PRECIO * m.CANTIDAD;
            var data = obj.Obtener(m.PRODUCTO.IDCATEGORIA);
            <tr>
                <td>@(id++)</td>
                <td>@(m.IDPEDIDO)</td>

                <td>@(data.NOMBRE)</td>
                <td>@(m.PRODUCTO.NOMBRE)</td>
                <td>@(m.PRECIO)</td>
                <td>@(m.CANTIDAD)</td>
                <td>@(m.PRECIO* m.CANTIDAD)</td>

            </tr>
        }
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>TOTAL</td>
        <td>@suma</td>

    </tr>
    </tbody>
</table>
<script>

    $(document).ready(function () {
        $('#Horizontal').DataTable({
            "scrollX": true
        });
    });

    $(document).ready(function () {
        $('#Vertical').DataTable({
            "scrollY": "200px",
            "scrollCollapse": true,
            "paging": false
        });
    });

    $(document).ready(function () {
        $('#Default').DataTable({
            "order": [[3, "desc"]]
        });
    });


    $(document).ready(function () {
        $("#DatatableP").DataTable({

            "aLengthMenu": [[2, 3, 5, 10, 25, 50, 100, 200, -1], [2, 3, 5, 10, 25, 50, 100, 200, "Todos"]],
            "bDestroy": true,
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ning?n dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "?ltimo",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });

        $('#ejemplo2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "aLengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "Todos"]]
        });

    });


</script>